name: DragonCoreGui
main: top.wcpe.dragoncoregui.DragonCoreGui
version: "${version}"
author: "WCPE QQ1837019522"
website: "https://github.com/wcpe"
softdepend:
  - "WcpeLib"
  - "DragonCore"
  - "EasyCore"
commands:
  dragoncoregui:
    description: main commands
    aliases:
      - "dcg"
      - "coregui"
    permission: "dragoncoregui.use"